
background            #0B0C0C
foreground            #b1baba
cursor                #b1baba
selection_foreground  #0B0C0C
color0                #0B0C0C
color1                #475155
color2                #576468
color3                #677575
color4                #6D7F7E
color5                #A35A73
color6                #B76D89
color7                #b1baba
color8                #7b8282
color9                #475155
color10               #576468
color11               #677575
color12               #6D7F7E
color13               #A35A73
color14               #B76D89
color15               #b1baba

